//
// Flavia study app
//
// Semantic aliases over the brand color tokens. The `brandOxblood`,
// `brandGold`, etc. symbols are auto-generated by Xcode from the
// matching color sets in Assets.xcassets — feature code should prefer
// the semantic aliases below so a future palette tweak only requires
// re-pointing the alias.
//

import SwiftUI


extension Color {
    static let brandPrimary = brandOxblood
    static let brandSecondary = brandGold
    static let brandNeutral = brandIvory
    static let brandSoftAccent = brandBlush
    static let brandText = brandEspresso
}
